#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
    source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
# Immediately execute commands from history (ex. !150)
setopt no_hist_verify


# Aliases
# alias dev='ssh gwong.dev.box.net -R "9000:localhost:9000"'
alias a='cd /box/etc/application'
alias i='cd /Users/gwong/workspace/infra'
alias de='cd /Users/gwong/deployment-config'
alias n='cd /box/www/box-notes'
alias nn='cd /box/www/box-notes-desktop'
alias c='cd /box/www/current_local'
alias sshn='ssh -t notes-app-gwong "cat /etc/motd; cd /home/gwong/box-notes; bash;"'
alias sshb='ssh bastion'
alias ll='ls -la'
alias work='echo "Use werk"'
alias history='history -f -100'
# On Mac: requires 'brew install coreutils'
alias readlink='greadlink'
# Always loading nvm slows down terminal startup
alias loadnvm='source $(brew --prefix nvm)/nvm.sh'

# begin devtools provisioning to setup local development

# Remove any existing /box/www/devtools_readonly/bin from the path
PATH=$(echo $PATH | sed 's/\/box\/www\/devtools_readonly\/bin[:]*//g')

# Remove any existing /usr/local/bin from the path
PATH=$(echo $PATH | sed 's/\/usr\/local\/bin[:]*//g')

# Add /usr/local/bin and /box/www/devtools_readonly/bin to the top of your PATH
export PATH=/usr/local/bin:/box/www/devtools_readonly/bin:$PATH
# end devtools provisioning

# Env variables
# Use vim as default editor
export VISUAL="vim"

# Java
export JAVA_8_HOME=$(/usr/libexec/java_home -v1.8)
export JAVA_11_HOME=$(/usr/libexec/java_home -v11)
export JAVA_17_HOME=$(/usr/libexec/java_home -v17)
alias java8='export JAVA_HOME=$JAVA_8_HOME'
alias java11='export JAVA_HOME=$JAVA_11_HOME'
alias java17='export JAVA_HOME=$JAVA_17_HOME'
# Use JDK 8 by default.
export JAVA_HOME=$JAVA_8_HOME
#export JAVA_HOME=$JAVA_11_HOME
#export JAVA_HOME=$JAVA_17_HOME

export NVM_DIR="$HOME/.nvm"
# Use latest (homebrew) version of bison (used to build thrift compiler
# from source, which is then used to build source code from thrift file)
# export PATH="/usr/local/opt/bison/bin:$PATH"
# export LDFLAGS="-L/usr/local/opt/bison/lib-L/usr/local/opt/openssl/lib"
# export CPPFLAGS="-I/usr/local/opt/openssl/include"
# export BOOST_ROOT="/usr/local/opt/boost"

# PATH
# Android NDK
#export PATH="$PATH:/Users/gwong/android-ndk-r17b"
# VS Code
export PATH="$PATH:/Applications/Visual Studio Code.app/Contents/Resources/app/bin"
# Misc.
export PATH="$PATH:/Users/gwong/bin"
# yarn (not needed with npm install yarn)
# export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
# ruby
export PATH="/usr/local/opt/ruby/bin:$PATH"
# FPM (ruby gem)
# export PATH="/usr/local/lib/ruby/gems/2.7.0/gems/fpm-1.14.2/bin:$PATH"
# PHP
export PATH="/opt/homebrew/opt/php@8.0/bin:$PATH"
export PATH="/opt/homebrew/opt/php@8.0/sbin:$PATH"
# Python
# export PATH="/usr/local/opt/python/libexec/bin:$PATH" # Not needed with brew install python
alias python=python3
# Force to use python 2 (Doesn't work with newer MacOS versions that no longer bundle python2)
# alias python3=python

# Terminal colors
if [[ -n "$ITERM_SESSION_ID" ]]; then
    tab-color() {
        echo -ne "\033]6;1;bg;red;brightness;$1\a"
        echo -ne "\033]6;1;bg;green;brightness;$2\a"
        echo -ne "\033]6;1;bg;blue;brightness;$3\a"
    }
    tab-red() { tab-color 255 0 0 }
    tab-green() { tab-color 0 255 0 }
    tab-blue() { tab-color 0 0 255 }
    tab-reset() { echo -ne "\033]6;1;bg;*;default\a" }

    function iterm2_tab_precmd() {
        # if [[ "$PWD" == "/box/www/box-notes" ]]; then
        #     tab-color 87 199 255
        # elif [[ "$PWD" == "/box/www/current_local" ]]; then
        #     tab-color 255 106 193
        # else
            tab-reset
        # fi
    }

    function iterm2_tab_preexec() {
        if [[ "$1" =~ "^ssh " ]]; then
            if [[ "$1" =~ "bastion" ]]; then
                tab-color 255 92 87
            elif [[ "$1" =~ "staging" ]]; then
                tab-color 243 249 157
            elif [[ "$1" =~ "dev" ]]; then
                tab-color 255 106 193
            fi
        elif [[ "$1" =~ "^sshn" ]]; then
            tab-color 87 199 255
        elif [[ "$1" =~ "^sshb" ]]; then
            tab-color 255 92 87
        else
            tab-reset
        fi
    }

    autoload -U add-zsh-hook
    add-zsh-hook precmd  iterm2_tab_precmd
    add-zsh-hook preexec iterm2_tab_preexec
fi

# Add confirmation to dangerous commands
git() {
    if [[ $@ == "stash clear" ]]; then
        echo "Are you sure you want to drop ALL stashes? [y/N]"
        read response
        case "$response" in
            [yY][eE][sS]|[yY])
               command git "$@"
                ;;
        esac
    elif [[ $@ == "stash drop" ]]; then
        echo "Are you sure you want to drop your stash? [y/N]"
        read response
        case "$response" in
            [yY][eE][sS]|[yY])
               command git "$@"
                ;;
        esac
    else
        command  git "$@"
    fi
}
